<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Affiliate extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'contact_email',
        'referral_code',
        'discount_percentage',
        'commission_rate',
        'status',
    ];

    /**
     * Get the referrals generated by this affiliate.
     */
    public function referrals()
    {
        return $this->hasMany(Referral::class);
    }
}